media:
  - name: gallery
    label: Gallery
    input: src/content/albums
    output: /src/content/albums
    extensions: [ png, webp, jpg, jpeg ]
  - name: static
    label: Static
    input: public/static
    output: /public/static
    extensions: [ png, webp, jpg, jpeg ]
  - name: posts
    label: Blog posts
    input: src/content/blog
    output: /src/content/blog
    extensions: [ png, webp, jpg, jpeg ]

content:
  - name: posts
    label: Posts
    path: src/content/blog
    type: collection
    fields:
       - name: title
         label: Title
         type: string
       - name: description
         label: Description
         type: string
         
       - name: draft
         label: Draft
         type: boolean
       - name: date
         label: Date
         type: date
       - name: tags
         label: Tags
         type: string
         list: true
       - name: image
         label: Image
         type: string
         default: ./1200x630.png
       - name: authors
         label: Author
         type: string
         list: true
         default: Brendan
       - name: body
         label: Body
         type: rich-text



   